version: "3.1"
services:
  odoo15:
    image: odoo:15.0
    depends_on:
      - db
      - pgadmin
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4-copy
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: lnote@outlook.es
       PGADMIN_DEFAULT_PASSWORD: odoo
       PGADMIN_LISTEN_PORT: 5432
    ports:
       - "8081:5432"
    links:
       - "db:pgsql-server"
volumes:
  odoo-web-data:
  odoo-db-data: