//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_PORRAJaime.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class APUESTAS
    {
        public int Id_apuesta { get; set; }
        public int Usuario { get; set; }
        public int Partido { get; set; }
        public string Apuesta { get; set; }
    
        public virtual PARTIDOS PARTIDOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
