package segundo;
// Generated 16-dic-2021 12:18:30 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Equipo generated by hbm2java
 */
public class Equipo implements java.io.Serializable {

	private String codequipo;
	private String denoequipo;
	private String entrenador;
	private String provincia;
	private Set jugadoreses = new HashSet(0);

	public Equipo() {
	}

	public Equipo(String codequipo) {
		this.codequipo = codequipo;
	}

	public Equipo(String codequipo, String denoequipo, String entrenador, String provincia, Set jugadoreses) {
		this.codequipo = codequipo;
		this.denoequipo = denoequipo;
		this.entrenador = entrenador;
		this.provincia = provincia;
		this.jugadoreses = jugadoreses;
	}

	public String getCodequipo() {
		return this.codequipo;
	}

	public void setCodequipo(String codequipo) {
		this.codequipo = codequipo;
	}

	public String getDenoequipo() {
		return this.denoequipo;
	}

	public void setDenoequipo(String denoequipo) {
		this.denoequipo = denoequipo;
	}

	public String getEntrenador() {
		return this.entrenador;
	}

	public void setEntrenador(String entrenador) {
		this.entrenador = entrenador;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public Set getJugadoreses() {
		return this.jugadoreses;
	}

	public void setJugadoreses(Set jugadoreses) {
		this.jugadoreses = jugadoreses;
	}

}
