package segundo;
// Generated 16-dic-2021 12:18:30 by Hibernate Tools 5.5.7.Final

import java.math.BigInteger;

/**
 * JugadoresId generated by hbm2java
 */
public class JugadoresId implements java.io.Serializable {

	private String equipo;
	private BigInteger codjugador;

	public JugadoresId() {
	}

	public JugadoresId(String equipo, BigInteger codjugador) {
		this.equipo = equipo;
		this.codjugador = codjugador;
	}

	public String getEquipo() {
		return this.equipo;
	}

	public void setEquipo(String equipo) {
		this.equipo = equipo;
	}

	public BigInteger getCodjugador() {
		return this.codjugador;
	}

	public void setCodjugador(BigInteger codjugador) {
		this.codjugador = codjugador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JugadoresId))
			return false;
		JugadoresId castOther = (JugadoresId) other;

		return ((this.getEquipo() == castOther.getEquipo()) || (this.getEquipo() != null
				&& castOther.getEquipo() != null && this.getEquipo().equals(castOther.getEquipo())))
				&& ((this.getCodjugador() == castOther.getCodjugador())
						|| (this.getCodjugador() != null && castOther.getCodjugador() != null
								&& this.getCodjugador().equals(castOther.getCodjugador())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEquipo() == null ? 0 : this.getEquipo().hashCode());
		result = 37 * result + (getCodjugador() == null ? 0 : this.getCodjugador().hashCode());
		return result;
	}

}
