package segundo;
// Generated 16-dic-2021 12:18:30 by Hibernate Tools 5.5.7.Final

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores implements java.io.Serializable {

	private JugadoresId id;
	private Equipo equipo;
	private String nya;
	private Byte edad;
	private Character grupo;

	public Jugadores() {
	}

	public Jugadores(JugadoresId id, Equipo equipo) {
		this.id = id;
		this.equipo = equipo;
	}

	public Jugadores(JugadoresId id, Equipo equipo, String nya, Byte edad, Character grupo) {
		this.id = id;
		this.equipo = equipo;
		this.nya = nya;
		this.edad = edad;
		this.grupo = grupo;
	}

	public JugadoresId getId() {
		return this.id;
	}

	public void setId(JugadoresId id) {
		this.id = id;
	}

	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	public String getNya() {
		return this.nya;
	}

	public void setNya(String nya) {
		this.nya = nya;
	}

	public Byte getEdad() {
		return this.edad;
	}

	public void setEdad(Byte edad) {
		this.edad = edad;
	}

	public Character getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Character grupo) {
		this.grupo = grupo;
	}

}
